### PR TITLE
Friendly message

### PR DESCRIPTION
**Pull request by dcanadillas**

### CODE REVIEW

**Comment by dcanadillas-kubecd** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **dcanadillas**

If they are not already assigned, you can assign the PR to them by writing `/assign @dcanadillas` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dcanadillas-kube%2Fgodemo-dc3).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dcanadillas-kube/godemo-dc3/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by dcanadillas-kubecd** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dcanadillas-kube/godemo-dc3/pull/2#issuecomment-468286691" title="Approved">dcanadillas</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dcanadillas-kube%2Fgodemo-dc3).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dcanadillas-kube/godemo-dc3/blob/master/OWNERS)~~ [dcanadillas]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by dcanadillas** [comment]
:star: PR built and available in a preview environment **dcanadillas-kube-godemo-dc3-pr-2** [here](http://godemo-dc3.jx-dcanadillas-kube-godemo-dc3-pr-2.35.187.39.22.nip.io)

**Pull request merged**
